[versions]
# plugings
kotlin = "1.9.0"
dokka = "1.8.20"
nexus = "1.3.0"
semver-git = "2.3.7"

lazysodium-java = "5.1.4"
coroutines = "1.7.3"
slf4j = "2.0.7"
jupiter = "5.10.0"
gson = "2.10.1"
tls-channel = "0.8.0"
jjwt = "0.11.5"
netty = "4.1.96.Final"

[libraries]

kotlin-lib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
kotlin-coroutines-lib = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines"}
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines"}

tls-channel = { group = "com.github.marianobarrios", name = "tls-channel", version.ref = "tls-channel" }
sodium = { group = "com.goterl", name = "lazysodium-java", version.ref = "lazysodium-java" }
jjwt-api = { group = "io.jsonwebtoken", name = "jjwt-api", version.ref = "jjwt" }
jjwt-impl = { group = "io.jsonwebtoken", name = "jjwt-impl", version.ref = "jjwt" }
jjwt-gson = { group = "io.jsonwebtoken", name = "jjwt-gson", version.ref = "jjwt" }

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jupiter" }
jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiter" }

netty-transport = { group = "io.netty", name = "netty-transport", version.ref = "netty" }
netty-http = { group = "io.netty", name = "netty-codec-http", version.ref = "netty" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus" }
semver-git = { id = "io.wusa.semver-git-plugin", version.ref = "semver-git" }

